services:
  - type: web
    name: jt-cadastro-fornecedores
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: APP_TIMEZONE
        value: America/Sao_Paulo
      - key: MAX_UPLOAD_MB
        value: 20
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: luiz_miranda
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        value: main
      - key: CLOUDFLARE_R2_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        sync: false
      - key: CLOUDFLARE_R2_PUBLIC_URL
        sync: false

